
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml




spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: @build.profile.id@
  application:
    name: ars
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB